CREATE TABLE `jsb`.`user` (`id` INT NOT NULL AUTO_INCREMENT , `steamkey` VARCHAR(30) NOT NULL , `ativo` VARCHAR(1) NOT NULL , `datacad` VARCHAR(10) NULL , `dataacesso` VARCHAR(10) NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;



CREATE TABLE `jsb`.`player` (`id` INT NOT NULL AUTO_INCREMENT , `steam` VARCHAR(50) NOT NULL , `ativo` INT(1) NOT NULL DEFAULT '0' , `datacadastro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`id`)) ENGINE = InnoDB; 